# Generated by Django 4.2.8 on 2024-01-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salespersons', '0002_salesperson_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='pic',
            field=models.ImageField(default='no_picture.jpg', upload_to='salespersons'),
        ),
    ]
