# Generated by Django 4.2.8 on 2024-02-01 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sale',
            table='sales',
        ),
    ]
